// react/src/App.jsx
// Replace this placeholder with your feature import as you build through the course.
//
//   import Compare from './features/compare/Compare.jsx'
//   import HundredPeople from './features/hundred-people/HundredPeople.jsx'
//   import Cartogram from './features/countries-cartogram/Cartogram.jsx'
//   import LanguageSpace from './features/language-space/LanguageSpace.jsx'
//
// Then render <Compare />, <HundredPeople />, etc. in the App return below.
import Compare from './features/compare/Compare.jsx'

export default function App() {
  return (
    <main className="min-h-screen bg-base-100 py-10 px-4 flex flex-col items-center gap-10">
      <div className="card bg-base-200 shadow-xl max-w-2xl w-full">
        <div className="card-body">
          <h1 className="card-title text-3xl">AI-Assisted Frontend Development Starter</h1>
          <p className="text-base-content/70">React 19 + Vite + Tailwind v4 + DaisyUI v5 + Vitest</p>

          <div className="divider"></div>

          <p>The scaffold is wired and the dev server runs. Time to build.</p>

          <ol className="list-decimal list-inside space-y-2 my-4">
            <li>
              Open the Lab course at{' '}
              <a
                className="link link-primary"
                href="https://neurons-lab.pages.dev/courses/ai-frontend-dev"
                target="_blank"
                rel="noopener noreferrer"
              >
                neurons-lab.pages.dev
              </a>
            </li>
            <li>Pick a module (Compare, 100 People, Cartogram, or Language Space)</li>
            <li>
              Create your feature file in <code className="badge">src/features/&lt;feature-name&gt;/</code>
            </li>
            <li>
              Replace the contents of <code className="badge">src/App.jsx</code> to import and render it
            </li>
            <li>
              Run <code className="badge">npm test</code> to check your work
            </li>
          </ol>

          <div className="alert alert-info">
            <span>
              Datasets are pre-shipped at <code>src/shared/data/regions.js</code>,{' '}
              <code>src/features/countries-cartogram/countries.js</code>, and{' '}
              <code>src/features/language-space/languages.js</code>. Don't try to author these by hand or have AI generate them: the lessons explain why.
            </span>
          </div>
        </div>
      </div>

      <div className="w-full max-w-5xl">
        <div className="text-center mb-4">
          <div className="badge badge-outline">Reference implementation</div>
          <p className="text-sm text-base-content/60 mt-2">
            Module 1 Compare ships pre-assembled in all three framework folders so the cross-framework parity is
            verifiable on first <code>npm run dev</code>. Diff{' '}
            <code>src/features/compare/Compare.&#123;vue,jsx,svelte&#125;</code> across the sibling folders to see
            the same UI rendered in each idiom. Remove the <code>&lt;Compare /&gt;</code> mount in{' '}
            <code>App.jsx</code> when you're ready to author your own.
          </p>
        </div>
        <Compare />
      </div>
    </main>
  )
}

// vue/src/App.vue
<script setup>
// Replace this placeholder with your feature import as you build through the course.
//
//   import Compare from './features/compare/Compare.vue'
//   import HundredPeople from './features/hundred-people/HundredPeople.vue'
//   import Cartogram from './features/countries-cartogram/Cartogram.vue'
//   import LanguageSpace from './features/language-space/LanguageSpace.vue'
//
// Then render <Compare />, <HundredPeople />, etc. in the template below.
import Compare from './features/compare/Compare.vue'
</script>

<template>
  <main class="min-h-screen bg-base-100 py-10 px-4 flex flex-col items-center gap-10">
    <div class="card bg-base-200 shadow-xl max-w-2xl w-full">
      <div class="card-body">
        <h1 class="card-title text-3xl">AI-Assisted Frontend Development Starter</h1>
        <p class="text-base-content/70">Vue 3 + Vite + Tailwind v4 + DaisyUI v5 + Vitest</p>

        <div class="divider"></div>

        <p>The scaffold is wired and the dev server runs. Time to build.</p>

        <ol class="list-decimal list-inside space-y-2 my-4">
          <li>Open the Lab course at
            <a
              class="link link-primary"
              href="https://neurons-lab.pages.dev/courses/ai-frontend-dev"
              target="_blank"
              rel="noopener noreferrer"
            >
              neurons-lab.pages.dev
            </a>
          </li>
          <li>Pick a module (Compare, 100 People, Cartogram, or Language Space)</li>
          <li>Create your feature file in <code class="badge">src/features/&lt;feature-name&gt;/</code></li>
          <li>Replace the contents of <code class="badge">src/App.vue</code> to import and render it</li>
          <li>Run <code class="badge">npm test</code> to check your work</li>
        </ol>

        <div class="alert alert-info">
          <span>
            Datasets are pre-shipped at
            <code>src/shared/data/regions.js</code>,
            <code>src/features/countries-cartogram/countries.js</code>, and
            <code>src/features/language-space/languages.js</code>.
            Don't try to author these by hand or have AI generate them: the lessons explain why.
          </span>
        </div>
      </div>
    </div>

    <div class="w-full max-w-5xl">
      <div class="text-center mb-4">
        <div class="badge badge-outline">Reference implementation</div>
        <p class="text-sm text-base-content/60 mt-2">
          Module 1 Compare ships pre-assembled in all three framework folders so the cross-framework parity is
          verifiable on first <code>npm run dev</code>. Diff
          <code>src/features/compare/Compare.{vue,jsx,svelte}</code> across the sibling folders to see the same
          UI rendered in each idiom. Remove the <code>&lt;Compare /&gt;</code> mount in <code>App.vue</code> when
          you're ready to author your own.
        </p>
      </div>
      <Compare />
    </div>
  </main>
</template>
